services:
    backend:
        container_name: technologia-cyborga-backend
        networks:
            - xcaddy
        build:
            context: ./backend/
        environment:
            - SPRING_PROFILES_ACTIVE=prod
    frontend:
        container_name: technologia-cyborga-frontend
        networks:
            - xcaddy
        build: 
            context: ./frontend/
        # depends_on:
            # - backend

networks:
    xcaddy:
        external: true
